workflows:
  android-apk:
    name: PGNEWS APK Build
    instance_type: linux
    max_build_duration: 60
    scripts:
      - name: Install dependencies
        script: npm install --force
      - name: Build Web Project
        script: npm run build
      - name: Build Android APK
        script: |
          npx cap sync android
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - lazarosetton@gmail.com
